### ISSUE TITLE
NullReferenceException using variables in custom functions

### ISSUE THREAD

**Issue by ArdenCarl** [dynamicexpresso/DynamicExpresso#284] opened 2023-05-05 13:51 UTC
We have a use case where we are defining our own custom **IF** function and then making use of it using an expression like so:

I**F(CUST1 != null, CUST1.Name, "Cust1 is null")**

The problem we are facing is when the **CUST1** variable turns out to be a null instance then we get a null reference exception when we call Interpreter.Eval for the expression.

Here's the complete code:

![image](https://user-images.githubusercontent.com/123397641/236476033-4d756234-ec02-4033-bbab-3d47d4a5dae0.png)

I've also attached the .cs file for it as a .txt file since I don't seem to be able to attach .cs files directly. See Tester.txt.

[Tester.txt](https://github.com/dynamicexpresso/DynamicExpresso/files/11406850/Tester.txt)

**Comment by davideicardi** [comment] 2023-05-06 13:12
Adding the relavant code here:

```
﻿using System;
using DynamicExpresso;

namespace DETest
{
    public class Tester
    {
        public class Customer
        {
            public string Name { get; set; }
        }

        public void Test()
        {
            var interpreter = new Interpreter();

            Func<bool, object, object, object> ifFunction = (b, x, y) => If(b, x, y);
            interpreter.SetFunction("IF", ifFunction);

            var cust1 = new Customer { Name = "Customer1" };

            interpreter.SetVariable("CUST1", cust1, typeof(Customer));

            // note. how I pass null for the CUST2 variable value here
            interpreter.SetVariable("CUST2", null, typeof(Customer));

            var exp1 = interpreter.Parse("IF(CUST1 != null, CUST1.Name, \"Cust1 is null\")").Expression;
            interpreter.SetExpression("EXP1", exp1);

            var exp2 = interpreter.Parse("IF(CUST2 != null, CUST2.Name, \"Cust2 is null\")").Expression;
            interpreter.SetExpression("EXP2", exp2);

            // this works
            System.Diagnostics.Debug.WriteLine(interpreter.Eval("EXP1"));

            // this throws an exception
            System.Diagnostics.Debug.WriteLine(interpreter.Eval("EXP2"));
        }

        private object If(bool b, object x, object y)
        {
            return b ? x : y;
        }
    }
}
```

**Comment by davideicardi** [comment] 2023-05-06 13:20
The problem is that the parameter is evaluated always, it is not dependent on the condition.

Why not using the standard `?:` conditional operator? Something like:
```
CUST2 != null ? CUST2.Name : "Cust2 is null"
```

**Comment by ArdenCarl** [comment] 2023-05-06 16:58
Many thanks for your prompt response @davideicardi.

As mentioned in my comment, we could use the ternary operator but the reason being our end users are much more familiar with Excel style functions. I guess it's asking a bit much for the interpreter to understand the desired IF function, which I appreciate. 

Is it at all possible to write an if/else statement? My users would understand this more. I have tried but do not seem to get it to work.

**Comment by davideicardi** [comment] 2023-05-12 15:08
Writing an `if/else` is not supported. Maybe you can try to do some kind of custom "pre processing" of the expression and convert the `IF() ` function to a ternary?

**Comment by hzy-6** [comment] 2023-11-25 12:53
You may need it https://github.com/ncalc/ncalc

**Comment by davideicardi** [comment] 2024-08-08 14:09
Closed as not planned.

**Closed by davideicardi** 2024-08-08 14:09 UTC
